data <- read.table("./household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?",colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'))
data$Date <- as.Date(data$Date,"%d/%m/%Y")
subdata <- subset(data,Date>=as.Date("2007/2/1")&Date<=as.Date("2007/2/2"))
datetme <- paste(subdata$Date,subdata$Time)
datetme <- as.POSIXct(datetme)
png("plot2.png")
plot(datetme,subdata$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab=" ")
dev.off()
