data <- read.table("./household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?",colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'))
data$Date <- as.Date(data$Date,"%d/%m/%Y")
head(data)
subdata <- subset(data,Date>=as.Date("2007/2/1")&Date<=as.Date("2007/2/2"))
datetime <- paste(subdata$Date,subdata$Time)
datetime <- as.POSIXct(datetime)
png("plot4.png")
par(mfrow=c(2,2))
plot(datetime,subdata$Global_active_power,ylab="Global Active Power",xlab=" ",type="l")
plot(datetime,subdata$Voltage,ylab="Voltage",xlab="datetime",type="l")
plot(datetime,subdata$Sub_metering_1,ylab="Energy Sub Metering",xlab=" ",type="l")
lines(datetime,subdata$Sub_metering_2,col="red")
lines(datetime,subdata$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty="solid")
plot(datetime,subdata$Global_reactive_power,ylab="Global_reactive_power",xlab="datetime",type="l")
dev.off()
